### ISSUE TITLE
"convert_epgm" = "false" breaks

### ISSUE THREAD

**Issue by youph** [data61/stellar-evaluation-plugins#11]
When using a pipeline with ["representation", "data splitter", "inference"] plugins, and posting a request to nai_scheduler_plugin with "convert_epgm": "true", everything works fine. However, when posting the same request with "convert_epgm": "false", I get the following error:

```
...
[2018-02-01 18:42:22,671: INFO/MainProcess] Received task: representation_learning[132c43da-b959-44ba-ab11-9224640200b9]  
[2018-02-01 18:42:22,674: INFO/ForkPoolWorker-2] Task 132c43da-b959-44ba-ab11-9224640200b9 [STARTED]: Starting task.
[2018-02-01 18:42:22,675: WARNING/ForkPoolWorker-1] 202
[2018-02-01 18:42:22,675: WARNING/ForkPoolWorker-1] ACCEPTED
[2018-02-01 18:42:22,676: WARNING/ForkPoolWorker-1] {'Location': 'http://localhost:5000/representation_learning/tasks/132c43da-b959-44ba-ab11-9224640200b9', 'Date': 'Thu, 01 Feb 2018 07:42:22 GMT', 'Content-Type': 'application/json', 'Server': 'Werkzeug/0.14.1 Python/3.5.4', 'Content-Length': '162'}
[2018-02-01 18:42:22,678: INFO/ForkPoolWorker-2] Loading the graph from /Users/tys017/Projects/Graph_Analytics/data/small-yelp-hin/small-yelp-hin.epgm/pred/temp/smallYelpExample_edgelist.txt...
[2018-02-01 18:42:22,685: INFO/ForkPoolWorker-2] Task representation_learning[132c43da-b959-44ba-ab11-9224640200b9] succeeded in 0.01180276300146943s: {'type': None, 'children': [], 'error': ['Traceback (most recent call last):
', '  File "/Users/tys017/Projects/Graph_Analytics/code/stellar-evaluation-plugins/plugins/nai_rl_learner_plugin.py", line 127, in read_graph
    G_epgm = EPGM(graph_file)
', '  File "/Users/tys017/Projects/Graph_Analytics/code/stellar-evaluation-plugins/utils/epgm.py", line 164, in __init__
    self.G = self.load(G)
', '  File "/Users/tys017/Projects/Graph_Analytics/code/stellar-evaluation-plugins/utils/epgm.py", line 111, in load
    raise Exception("Path {} does not exist!".format(path))
', 'Exception: Path /Users/tys017/Projects/Graph_Analytics/data/small-yelp-hin/small-yelp-hin.epgm/pred/temp/smallYelpExample_edgelist.txt does not exist!
', '
During handling of the above exception, another exception occurred:

', 'Traceback (most recent call last):
', '  File "/Users/tys017/Projects/Graph_Analytics/code/stellar-evaluation-plugins/stellar_server/celery_tasks.py", line 45, in __call__
    result = super().__call__(*args,...', ' ...', ...]}
```

**Comment by PantelisElinas** [comment]
This pipeline requires that the data splitter receives .lab as input. If you set the convert_epgm flag to false then no such file is produced by the scheduler plugin so it naturally fails when it tries to load the data. The option convert_epgm = False is only valid for a pipeline with GCN (once we have the latter plugin developed.)

**Comment by PantelisElinas** [comment]
So, as we discussed, when using a pipeline with GCN, then convert_epgm should be set to False. Pipelines that don't use GCN have to set this parameter to True.

We have no way of enforcing this at the moment, so we depend on the users creating a valid pipeline specification file.
