### ISSUE TITLE
PURGE request error

### ISSUE THREAD

**Issue by youph** [data61/stellar-evaluation-plugins#6]
When asking to PURGE a task server's queue, the following error is returned:
```
curl http://0.0.0.0:5000/nai_scheduler/tasks/ -X PURGE


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by youph** [comment]
Fixed by YT on 30 Jan 2018

**Comment by youph** [comment]
Now when a PURGE request is sent to a nai_scheduler task queue (running on Flask+Celery backend server), the tasks are deleted (including the sub-tasks spawned by the nai_scheduler task), but the following error is thrown on the server side:

PURGE request:
```
curl http://localhost:5000/nai_scheduler/tasks/ -X PURGE
```

Error thrown by stellar-server:
```
WARNING:root:Argument task_id not in default client message.
WARNING:root:Argument task_id not in default client message.
[2018-02-09 11:38:20,380] ERROR in app: Exception on /nai_scheduler/tasks/ [PURGE]
Traceback (most recent call last):
  File "/Users/tys017/anaconda3/envs/stellars/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tys017/anaconda3/envs/stellars/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tys017/anaconda3/envs/stellars/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tys017/anaconda3/envs/stellars/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/tys017/anaconda3/envs/stellars/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tys017/anaconda3/envs/stellars/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tys017/Projects/Graph_Analytics/code/stellar-evaluation-plugins/stellar_server/server_celery.py", line 185, in purge_tasks
    return make_response(None, 204, {})
  File "/Users/tys017/anaconda3/envs/stellars/lib/python3.5/site-packages/flask/helpers.py", line 191, in make_response
    return current_app.make_response(args)
  File "/Users/tys017/anaconda3/envs/stellars/lib/python3.5/site-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

The client that sent the PURGE request gets the following response:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```
